<?php
/**
 * @file
 * Athorized.net Payment Getaway functionality for POS sales.
 */

/**
 * Implemet hook_menu.
 */
function commerce_pos_authorize_net_card_present_menu() {
  $items = array();
  $items['pos/sale/auth-payment'] = array(
    'title' => 'Authorize.net Payment',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_pos_authorize_net_card_present_page_display'),
    'access callback' => '_commerce_pos_access_check',
    'access arguments' => array('process commerce pos sales'),
    'file' => 'includes/commerce_pos_online_auth.payment.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Commerce_pos_authorize_net_card_present.module.
 */
function commerce_pos_authorize_net_card_present_form_commerce_pos_sale_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_id, array('commerce_pos_sale', 'commerce_pos_return'))) {
    _commerce_pos_authorize_net_card_present_transaction_form_alter($form, $form_state);
  }
}

/**
 * File _commerce_pos_authorize_net_card_present_transaction_form_alter.
 */
function _commerce_pos_authorize_net_card_present_transaction_form_alter(&$form, &$form_state) {
  $order_wrapper = !empty($form_state['order_wrapper']) ? $form_state['order_wrapper'] : FALSE;
  if ($order_wrapper) {
    $line_items = $order_wrapper->commerce_line_items->value();
    $has_active_transaction = !empty($line_items);
  }
  else {
    $has_active_transaction = FALSE;
  }
  if ($has_active_transaction) {
    if (!empty($form['transaction_options']['actions'])) {
      $form['transaction_options']['actions']['payment2'] = array(
        '#type' => 'submit',
        '#value' => t('Authorize.net card Payment'),
        '#attributes' => array(
          'class' => array('commerce-pos-btn-pay-green'),
        ),
        // This won't do anything without form_keybinds installed.
        '#weight' => 101,
        '#key_binds' => array('F7'),
        '#submit' => array('commerce_pos_authorize_net_card_present_transaction_pay_submit'),
      );
    }
  }
}

/**
 * Commerce_pos_authorize_net_card_present_transaction_pay_submit.
 */
function commerce_pos_authorize_net_card_present_transaction_pay_submit($form, &$form_state) {
  if (!empty($form_state['values']['transaction_options']['customer'])) {
    // Attempt to associate the transaction with a customer.
    $email_address = $form_state['values']['transaction_options']['customer'];

    if ($user = user_load_by_mail($email_address)) {
      if ($form_state['transaction']->doAction('setOrderCustomer', $user)) {
        // Only save if if the order customer was actually updated.
        $form_state['transaction']->doAction('saveOrder');
      }
    }
  }
  $form_state['transaction']->doAction('save');
  $form_state['redirect'] = 'pos/' . $form['#redirect_key'] . '/auth-payment';
}
